### ISSUE TITLE
File has not aged enough yet. Will return nothing

### ISSUE THREAD

**Issue by stenzelk96** [nuggetman/smb-connector#10]
Hi Nuggetman,

currently we face problems regarding the SMB connector: [org.mul.mod.smb.int.SmbClient] [The file has not aged enough yet, will return nothing for: abc.pdf] so the payload after this connector is of type org.mule.transport.NullPayload.
We get the list of files to read from SMB through the SMB directory list command. Is it possible to configure directory list to only list files older than a specified age?

**Comment by nuggetman** [comment]
should be do-able, investigating

**Comment by nuggetman** [comment]
this will be addressed in the next release, this will require the addition of a new parameter, so existing projects using the connector will need to have their config updated.

**Comment by stenzelk96** [comment]
Thanks. Pls keep me updated when you are about to release next version :)

**Comment by nuggetman** [comment]
Am working out the kinks at the moment and will release a new edition within the week that should resolve this and some of the other issues, I can link a pre-release edition here if you would be willing to test it.
