### ISSUE TITLE
Polling on SMB connector as source endpoint polls existing files multiple times

### ISSUE THREAD

**Issue by Anomitro95** [nuggetman/smb-connector#11]
Hey nuggetman,

I was using polling over smb connector as source and wanted to use the directory list operation and the files that I was getting for **each poll was a repetition of the set of files present in the shared network directory**. For every poll the files are repeated in an erratic manner.
So for one poll the set of files will repeat 3 times, and for the next it will repeat for 2 times. 
I have used synchronous as the processing strategy for the flow so that a thread waits for all files to be read from the directory once before polling again. I have used the idempotence filter to get the unique files but polling is creating these extensive amount of reads on the server which means the traffic load is exceeding by a lot which is creating trouble. 
Please get back to me as soon as possible. We are using Mule 3.8.4

Best Regards,
Anomitro Mukherjee

**Comment by nuggetman** [comment]
Have not seen this, but will investigate

**Comment by Anomitro95** [comment]
Please do, thanks for your prompt response!

**Comment by nuggetman** [comment]
I have not been able to reproduce this, can you share some details on the JVM version, OS Mule is running on and OS version for the SMB shared folder?

**Comment by Anomitro95** [comment]
The required information is given below :
>JVM version on doing a java -version check is 1.8.0_181
>Mule is running on  64 bit OS Windows Server 2012R2
>on doing a sc.exe query on powershell I found out that mrxsmb10 and mrxsmb20 have status 4 and running for shared network directory

**Comment by nuggetman** [comment]
Am still unable to reproduce the error. The next release of the connector is undergoing certification and uses a different underlying library, this will likely resolve the issue.

**Comment by nuggetman** [comment]
Please try the v1.2.0 edition of the connector, it contains many fixes & updates: https://www.mulesoft.com/exchange/org.mule.modules/smb-connector/
