### ISSUE TITLE
add support for jcifs-ng

### ISSUE THREAD

**Issue by nuggetman** [nuggetman/smb-connector#12]
The jcifs is in maintenance only-mode, jcifs-ng is a new alternative that is actively worked on and provides greater support for SMBv3.

**Comment by ucsfel** [comment]
Hi nuggetman,

SMB/1 has been turned off in our network and will be needing support for SMBv3.  Any estimates on when this SMBv3 feature will be available?

**Comment by nuggetman** [comment]
am targeting April

**Comment by nuggetman** [comment]
SMBv3 requires JCFIS-NG which has library conflicts in Mule 3, now has a dependency on a Mule 4 edition.

**Comment by nuggetman** [comment]
A Mule 4 edition of the SMB connector has been released here: https://www.mulesoft.com/exchange/com.mulesoft.connectors/mule-smb-connector/
