### ISSUE TITLE
unable to connect

### ISSUE THREAD

**Issue by piyushinvenio** [nuggetman/smb-connector#13]
Hi,
i am getting the above exception while connecting through SMB connector. can anyone please help me out in resolving the same on urgent basis.

**Comment by nuggetman** [comment]
This could the hostname not resolvable or the share path name is incorrect

**Comment by nuggetman** [comment]
Original issue label:
org.mule.retry.notifiers.ConnectNotifier: Failed to connect/reconnect: Work Descriptor. Root Exception was: The network name cannot be found.. Type: class jcifs.smb.SmbException
