### ISSUE TITLE
Share path not accepting subfolders/multiple sub directories

### ISSUE THREAD

**Issue by vimal7225s** [nuggetman/smb-connector#17]
Hi,

SMB connector is working when share path has single name like "DFS" under **share** field. But if I provide sub folder names like "DFS\SubFolder1\SubFolder2" it is failing with connection exception error.

Am I missing something while updating the shared path for multiple sub-folders or the feature to include multiple folders under **share** field is not yet in place.

### **SMB Multiple Shared Folder with BackSlash(\\)**

![smb_multiple_shared_folder_backwardslash](https://user-images.githubusercontent.com/36211084/65636884-c25ec000-dfa8-11e9-8446-d3358da6f452.JPG)

### **SMB Multiple Shared Folder with Forward Slash(/)**

![smb_multiple_shared_folder_forwardslash](https://user-images.githubusercontent.com/36211084/65636885-c25ec000-dfa8-11e9-90f8-14ee639eeab2.JPG)

### **SMB Single Shared Folder without any slashes**

![smb_single_shared_folder](https://user-images.githubusercontent.com/36211084/65636886-c25ec000-dfa8-11e9-91c7-df3ea4b51def.JPG)

**Comment by nuggetman** [comment]
With the share name set as the root share path used and then one can use subfolder parameters in the connector operations to get down lower (e.g. in a file get), this mimics the current behaviour found in SMBJ (the underlying SMB library) where share names cannot contain a "\".
