### ISSUE TITLE
Getting "Failed to invoke directoryList" always after deploying in On-prem and Local deployment.

### ISSUE THREAD

**Issue by deepareekabinaz** [nuggetman/smb-connector#24]
Hi,

Since path 3 days I have been trying to use SMB connector Version 1.2.X in mule 3.9.4. However, i am continuously getting "Failed to invoke directory" for the Directory List operation I am trying to use. The host and password is fine, i have checked the path is also fine. Is it because lack of access rights to the particular directory ? I am pasting the error logs I am getting in OnPrem env:

*********************************************************************
2020-09-14 07:09:31,726 [pool-565-thread-1] INFO  com.hierynomus.smbj.connection.Connection - Successfully connected to: 127.91.313.70
2020-09-14 07:09:31,994 [pool-565-thread-1] INFO  com.hierynomus.smbj.connection.Connection - Successfully authenticated grvGfLmuledev_AZ on 127.91.313.70, session is 149859193585769
2020-09-14 07:09:31,996 [pool-565-thread-1] INFO  com.hierynomus.smbj.session.Session - Connecting to \\127.91.313.70\I/DRIFT/FromDrift/GH10073 on session 149859193585769
2020-09-14 07:09:32,008 [pool-565-thread-1] ERROR org.mule.retry.notifiers.ConnectNotifier - Failed to connect/reconnect: Work Descriptor. Root Exception was: STATUS_BAD_NETWORK_NAME (0xc00000cc): Could not connect to \\127.91.313.70\I/DRIFT/FromDrift/GH10073. Type: class com.hierynomus.mssmb2.SMBApiException
2020-09-14 07:09:32,019 [pool-565-thread-1] ERROR org.mule.exception.DefaultMessagingExceptionStrategy - 
********************************************************************************
Message               : Failed to invoke directoryList.
Element               : null
--------------------------------------------------------------------------------
Exception stack is:
Failed to invoke directoryList. (org.mule.api.MessagingException)
  com.hierynomus.smbj.session.Session.connectTree(Session.java:180)
  com.hierynomus.smbj.session.Session.connectShare(Session.java:151)
  org.mule.modules.smb.internal.SmbClient.setShare(SmbClient.java:570)
  org.mule.modules.smb.internal.SmbClient.connect(SmbClient.java:199)
  org.mule.modules.smb.config.SmbConnectorConfig.connect(SmbConnectorConfig.java:264)
  (42 more...)

  (set debug level logging or '-Dmule.verbose.exceptions=true' for everything)

Moreover, I wanted to know that can we deploy the SMB connector on cloudhub or not ?

Also I am attaching the screenshot for the logs I got on local. 
![Local logSMB](https://user-images.githubusercontent.com/58976029/93193813-ddd15680-f736-11ea-82a2-ea5355bbcbe9.PNG)

**Comment by Deep075** [comment]
Hi Alex,

Can you please help with the above issue. We are able to connect with version 1.0.0 as last checked but no success with the version 1.2.0. Please help as we are in a deadlock and need to move forward.

@nuggetman  @connectors-cert-ci

**Comment by nuggetman** [comment]
The error in the first log is caused by the STATUS_BAD_NETWORK_NAME, which would be host or share path name issues. The log in the second case shows a network connection timeout.

**Comment by deepareekabinaz** [comment]
Hi Alex,
As mentioned it seems to work fine with version 1.0.0 but getting the "Failed to invoke Directory" for version 1.2.0 In my studio or through exchange i.e. only able to use version 1.2.0.
Are there any jars or files for which might be missing and where i can get them? Or else shall i try to use version 1.0.0 ? 
@nuggetman

**Comment by nuggetman** [comment]
Any jars are packaged with connector and anything missing would manifest in a very different error. Older editions use a different underlying library and have issues that have since been resolved. Can you elaborate on the nature of the share, i.e. is it DFS based or a regular windows share?

**Comment by deepareekabinaz** [comment]
Hi Alex,
Hope you are doing good.
This is regular windows based share.  Can you please tell is is fine to connect the SMB on local, cloudhub or on prem? Is there any problem in deploying in any one of the above ? Moreover, please check the way I have configured the connector(I have not given any Wild Card name).
Can you please tell why am I getting connection timed out. I am keeping timeout value as 50000 ms. What i can do to resolve the timeout error.

![ConnectorConfig](https://user-images.githubusercontent.com/58976029/93598581-673d8e80-f9ac-11ea-978f-1abe7eb5a8d4.PNG)
![Connector_config2](https://user-images.githubusercontent.com/58976029/93598591-6ad11580-f9ac-11ea-990a-e03ad413096e.PNG)


![Connection_timed_out](https://user-images.githubusercontent.com/58976029/93597713-05c8f000-f9ab-11ea-8d77-77bea59146f8.PNG)

@nuggetman

**Comment by nuggetman** [comment]
The certification process involves testing out the connectivity from different locations, there are no known issues connecting from CloudHub vs On-prem vs Studio. The error in the latest screenshot is likely a network/firewall related one as it shows a timeout at the socket connection level, i.e. IP & Port connectivity problem. Enabling debug logging may yield some additional clues.

**Comment by deepareekabinaz** [comment]
Hi Alex,

I am able to connect via onprem but still getting issues on Cloudhub and Local deployment. Can you please confirm the package i can use to enable debug logs.

**Comment by deepareekabinaz** [comment]
Hi Alex,
Finally I am able to connect to the specific directory. But as soon as the connection is established it is closing again. I am attaching the log snippet please have a look and suggest the probable cause. Your inputs are really helping me to move forward with this .
![Connection Closed](https://user-images.githubusercontent.com/58976029/93918432-dd6b2980-fcfb-11ea-9172-d0b8c41de544.PNG)
@nuggetman

**Comment by nuggetman** [comment]
Debug logging is enabled by adding this section into the log4j2.xml inside the <loggers> section:

AsyncLogger name="org.mule.modules.smb" level="DEBUG"

**Comment by deepareekabinaz** [comment]
Hi alex,
Can you please give the exact module name to be included in log4j2.xml to get the debug logs enabled ?

@nuggetman
