### ISSUE TITLE
java.net.UnknownHostException

### ISSUE THREAD

**Issue by HariprasathUdayakumar** [nuggetman/smb-connector#26]
Hello, Good day.

We are using SMB connector in one of our business critical applications for the client. In the past month we have been facing disconnections to connect to the source system. It fails with the error "java.net.UnknownHostException". Here is the error stack:

org.mule.exception.DefaultMessagingExceptionStrategy - 
********************************************************************************
Message               : Failed to invoke directoryList.
Payload               : 
Payload Type          : java.lang.String
--------------------------------------------------------------------------------
Root Exception stack trace:
jcifs.smb.SmbException: Failed to connect to server
java.net.UnknownHostException: *hostName*

Could you please help us with this? How can we fix the issue "java.net.UnknownHostException"? Once we restart the application the connection is working fine. We are using SMB 1.0 connector.

Regards,
Hariprasath Udayakumar.

**Comment by nuggetman** [comment]
This is typically a DNS issue, java.net.UnknownHostException means the hostname could not be resolved into an IP, this is not something that can be resolved in the connector.
