### ISSUE TITLE
Files are not picked from the SMB polling

### ISSUE THREAD

**Issue by HariprasathUdayakumar** [nuggetman/smb-connector#27]
Hi Alex, Good day.

We are using SMB connector in our application to pick critical payment files from IT2 system. Currently the files that are placed in the folders are not getting picked up by MuleSoft even though the polling is occurring. This is causing huge impacts to the client. Is there any way if possible for us to connect with you to troubleshoot the incident? There is complete outage currently.

Regards,
Hariprasath Udayakumar.

**Comment by nuggetman** [comment]
Best next step is to enable debug logging by adding this section into the log4j2.xml with appropriate XML open/close tags:

AsyncLogger name="org.mule.modules.smb" level="DEBUG"
