### ISSUE TITLE
Slow polling of files 

### ISSUE THREAD

**Issue by NayanaNanjundappa** [nuggetman/smb-connector#28]
Hi Team,

We have used SMB connector for a file poller functionality in one of the mule3 application. From few weeks/months this polling of files have become very slow(Configured to fetch every 2 minutes), now its taking almost 4-6 hours. any help would be much appreciated

**Comment by nuggetman** [comment]
Best next step is to enable debug logging by adding this section into the log4j2.xml with appropriate XML open/close tags:

AsyncLogger name="org.mule.modules.smb" level="DEBUG"

The debug logs should provide some clues as to where the issues is coming from.
