### ISSUE TITLE
Support MuleSoft 4.x

### ISSUE THREAD

**Issue by dennypc** [nuggetman/smb-connector#5]
Hi,

Will this connector be supporting MuleSoft 4.1 soon?  If not, are you open to PRs?

Thanks!

**Comment by nuggetman** [comment]
Happy to do a PRs in general, though am working on a Mule 4 edition shortly

**Comment by ashwathrn** [comment]
I would like to use the SMB connector for Mule 4. Please let me know when the connector wold be ready.

**Comment by tania-22** [comment]
Hi,

I am currently developing an application using Mule runtime version 4.1.4 and would like to use SMB connector for writing files to a fileshare location from CloudHub. Could you please let me know by when will the SMB connector be available for the latest Mule runtime version.

Thanks & Regrads,
Tania Chakraborty.

**Comment by Enates** [comment]
Hi,
We are looking for the connector for Mule4. Please kindly advise when it will be available.

**Comment by Skanakam9** [comment]
Hi, 
We are looking forward for SMB connector for Mule 4.x version. May we know when it will be available.
Thanks for your efforts.

**Comment by DineshSaini798** [comment]
Hi, I am currently developing a application in Mule 4.x where I need to read files and write on Window network drive . I would like to use the SMB connector for same . Can you please let me know where I can find the details for SMB connector and how it can be available for me . Thanks

**Comment by nuggetman** [comment]
A Mule 4 edition of the SMB connector has been released here: https://www.mulesoft.com/exchange/com.mulesoft.connectors/mule-smb-connector/
