### ISSUE TITLE
SMB-Connector does not work with public SMB Shares

### ISSUE THREAD

**Issue by stenzelk96** [nuggetman/smb-connector#8]
Hi nuggetman,

In our company we often use public SMB Shares (no user authentication is required).
Unfortunately your connector requires user authentication. Filling fields with blank space does not work either. Are you able to provide an option for public smb shares?
In our company we use Mule Runtime 3.8.7.
I'm really looking forward to hearing from you.

**Comment by nuggetman** [comment]
Interesting use case, I will need to check on the jcifs library and see if it supports connections with no auth.

**Comment by stenzelk96** [comment]
Hi nuggetman,
thanks for reviewing. Please keep me updated

**Comment by nuggetman** [comment]
anonymous connectivity is supported, will be in the next release (in progress).

**Comment by nuggetman** [comment]
jcifs default library disables anonymous connectivity under the covers as it was deemed insecure by the jcifs developer. Will need to switch out the underlying connectivity library to support this.

**Comment by nuggetman** [comment]
resolved in v1.2.0
