### ISSUE TITLE
SMB-Connector does not provide delete on read option

### ISSUE THREAD

**Issue by stenzelk96** [nuggetman/smb-connector#9]
Hi nuggetman,

is there any possibility to provide an delete on read operation through smb connector?
Currently we need to use smb connector twice: First to read file and then again to delete it after it has been loaded successfully.

**Comment by nuggetman** [comment]
This should be reasonable, will add into the next release.

**Comment by nuggetman** [comment]
Apologies, been a while since I checked the code. There is a delete on read available today, it is a boolean setting under the file read operation.

**Comment by stenzelk96** [comment]
Hi nuggetman,
thx for your quick response. When the new version is available on Exchange I will test functionality asap.

**Comment by stenzelk96** [comment]
Hi,
I tested delete on read functionaliy.
One problem remains (maybe in correlation with issue #10 ): It unfortunately deletes files which are not older than specified age..

**Comment by nuggetman** [comment]
In the current release the file age parameter is attached to the read operation, in order to support it on the other operations I can add it to each place or add it as a global config parameter for use across all operations?

**Comment by stenzelk96** [comment]
Hi,
I would suggest to use it as a global parameter
